import type { z } from 'zod'
import type { EnvSchema } from './types'

// Generates a .env.example file content string from a schema.
// Inspects the Zod schema's _def to produce a sensible placeholder
// per type, and marks optional fields clearly.

export function generateEnvExample(schema: EnvSchema): string {
  const lines: string[] = [
    '# Generated by envguard — fill in real values, do not commit this file',
    '',
  ]

  for (const key of Object.keys(schema)) {
    const fieldSchema = schema[key]
    const placeholder = inferPlaceholder(fieldSchema)
    const isOptional = fieldSchema.isOptional()

    if (isOptional) lines.push(`# Optional`)
    lines.push(`${key}=${placeholder}`)
    lines.push('')
  }

  return lines.join('\n')
}

function inferPlaceholder(schema: z.ZodTypeAny): string {
  // Zod's internal `_def` shape isn't part of the public type surface,
  // so `any` is required here to read `typeName`/`checks`/`values`.
  const typeName = (schema._def as any).typeName

  switch (typeName) {
    case 'ZodString': {
      const checks = (schema as z.ZodString)._def.checks ?? []
      if (checks.some((c: any) => c.kind === 'url')) return 'https://example.com'
      if (checks.some((c: any) => c.kind === 'email')) return 'user@example.com'
      return 'value'
    }
    case 'ZodNumber':
      return '0'
    case 'ZodBoolean':
      return 'true'
    case 'ZodEnum': {
      const values = (schema as z.ZodEnum<[string, ...string[]]>)._def.values
      return values[0] ?? 'value'
    }
    case 'ZodOptional':
      return inferPlaceholder((schema as z.ZodOptional<z.ZodTypeAny>)._def.innerType)
    case 'ZodDefault':
      return inferPlaceholder((schema as z.ZodDefault<z.ZodTypeAny>)._def.innerType)
    default:
      return 'value'
  }
}
